### ISSUE TITLE
Nodes are generated in more layers than intended one foreground layer

### ISSUE THREAD

**Issue by WSDguy2014** [AiTechEye/mt2d#4]
I was playing this mod in Minetest version 5.2.0, and I encounter trees that are placed in more layers stacked on top of intended 1 front layer only.
![image](https://github.com/AiTechEye/mt2d/assets/13905392/1e1eb322-8f45-495f-9709-be9d7cb66bd0)
Same thing for planting trees that are done by players.
![image](https://github.com/AiTechEye/mt2d/assets/13905392/74283ba3-bee3-4c61-ab10-f7db7d557e44)
And at one point even naturally generates and replaces at the same layer as a background layer, and it also can be removed and gathered.
![image](https://github.com/AiTechEye/mt2d/assets/13905392/99201493-2588-4980-a11e-d1185a3d14f7)

mt2d mod version: 2.7 [MT 5.0+] (116 KB)
World seed: `5487536256439323842`

This needs to be fixed by replacing with air nodes and background nodes (if the background layer node happens to be replaced by a naturally generated tree, such as jungle trees) in a range that is farther before players can able to reach and gather resources in time from more front layers than one and in the same breakable node as the background layer.

**Comment by AiTechEye** [comment]
How often does it happen?
if it only happens sometimes it maybe not worth it.

This is caused by schematics, cuz the generator is already replacing everything outside the map blob/master/init.lua#L364
I guess it is happens immidly after the map generated, but doublechecking would cost some preformence and memory, cuz it the fix have to happen outside register_on_generated()
It is just to add every single generated air node to a list then replace them again.

**Comment by WSDguy2014** [comment]
> How often does it happen?

Uncommonly. More trees that are naturally generated (especially in forests, such as jungles), greater chance of happening.
It's a shame that you would not able to fix it without somehow rewriting the code and finding a way to optimizing it.
I play on mapgen v7, so, I'm not sure if it works better by implementing own 2D world generation and structures to this mod that is best designed and played with a singlenode mapgen.

**Comment by AiTechEye** [comment]
i forget register_lbm exists, it removes all of them easily https://github.com/AiTechEye/mt2d/commit/4843faf7300006e20fcc5ebcf276e74bc7000d31

i also added functions that updates the player's fly/noclip ability already when the privs are granted/revoked, instead of having to rejoin
