### ISSUE TITLE
Problems with beds

### ISSUE THREAD

**Issue by WSDguy2014** [AiTechEye/mt2d#6]
Wanted to skip a night time, but I found few problems with beds:
1. Placing a bed would not use an item from the player's inventory.
2. Removing the place-down bed would drop itself instead of a normal corresponding bed item, creating a bed duplication, despite I only have damage enabled.
3. Placing a bed near a node can get kicked out to main menu with `ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Expecting itemstack, itemstring, table or nil. item=beds:fancy_bed_bottom`.

And the same thing occurs with a fancy bed variant, which is showcased in this video here:

https://github.com/AiTechEye/mt2d/assets/13905392/34f3c27f-665b-4e47-b93b-995edda224dd

mt2d mod version: 2.7 [MT 5.0+] (116 KB)

**Comment by AiTechEye** [comment]
fixed, even that you could place stuff in the bed, and it checked wrong side so you couldn't place it into walls to right.
