### ISSUE TITLE
[Enhancement] Toggle ability to point player self on/off

### ISSUE THREAD

**Issue by WSDguy2014** [AiTechEye/mt2d#8]
Trying to pick up dropped items up close will instead hit the player themselves without moving away a bit from the dropped item object.

![image](https://github.com/AiTechEye/mt2d/assets/13905392/4c130226-b764-4f4d-abba-3b1512f040c3)

Not sure if it's going to have a button in the inventory window to disable/enable ability to point to a player self. Would be a good gameplay improvement even for touchscreen phone/tablet players.

**Comment by WSDguy2014** [comment]
> the only problem is that other players can't point you, annoying things/fights will happen.

That could a potential effect if disabling PvP, so players can't hit each other directly. You could implemented it for a client-side behavior, so the player can avoid only hitting themselves trying to pick up dropped items and have still get hit and taken damage by other players, so they can point at the other player, and can fight back.


> instead i added so you picks up the items around you when you punch yourself

Alright, that's ok to implement that, I'm fine with that choice you made.

**Comment by AiTechEye** [comment]
you cant select what is pointing you, cuz the entities/objects only have the option: pointable on or off.
it could be a floating shield in front of you, but sounds pretty wierd, so i guess we already have the best option now, it is not uncommon to pick up items in this way.
